# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DryRun' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DryRun
  pod 'AppCenter/Crashes', '~> 1.8.0'
  pod 'AppCenter/Analytics', '~> 1.8.0'
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  

  platform :ios, '9.0'
  target 'DryRunTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DryRun-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DryRun-tvOS

  target 'DryRun-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
